In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [16]:
dataset = pd.read_csv(r"C:\Users\acer\Documents\misdocumentos\MATERIAL DE ESTUDIO\model_clasification\trees_clasification\bill_authentication.csv")
dataset

      Variance  Skewness  Curtosis  Entropy  Class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [17]:
dataset.shape

(1372, 5)

In [18]:
dataset.head()

   Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [21]:
X = dataset.drop('Class', axis=1)
X

      Variance  Skewness  Curtosis  Entropy
0      3.62160   8.66610   -2.8073 -0.44699
1      4.54590   8.16740   -2.4586 -1.46210
2      3.86600  -2.63830    1.9242  0.10645
3      3.45660   9.52280   -4.0112 -3.59440
4      0.32924  -4.45520    4.5718 -0.98880
...        ...       ...       ...      ...
1367   0.40614   1.34920   -1.4501 -0.55949
1368  -1.38870  -4.87730    6.4774  0.34179
1369  -3.75030 -13.45860   17.5932 -2.77710
1370  -3.56370  -8.38270   12.3930 -1.28230
1371  -2.54190  -0.65804    2.6842  1.19520

[1372 rows x 4 columns]

In [20]:
y = dataset['Class']
y

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [23]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [25]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int64)

In [26]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[162   0]
 [  1 112]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       162
           1       1.00      0.99      1.00       113

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275

In [27]:
X_test

      Variance  Skewness  Curtosis   Entropy
53     2.54900  6.149900  -1.16050 -1.237100
742    0.66191  9.659400  -0.28819 -1.663800
272    4.40720 -0.070365   2.04160  1.131900
1117  -1.98810  0.999450  -0.28562 -0.700440
554    2.64630 -4.815200   6.35490  0.003003
...        ...       ...       ...       ...
300    0.32920 -4.455200   4.57180 -0.988800
331    2.04210  1.243600   4.21710  0.904290
288    0.44125  2.948700   4.32250  0.715500
58     3.13770 -4.109600   4.57010  0.989630
539    4.24750  1.481600  -0.48355  0.953430

[275 rows x 4 columns]

In [32]:
df = pd.DataFrame(y_pred, columns = ['predict'])
df

     predict
0          0
1          0
2          0
3          1
4          0
..       ...
270        0
271        0
272        0
273        0
274        0

[275 rows x 1 columns]

In [33]:
df_index = pd.merge(df, X_test, right_index=True, left_index=True)
df_index

     predict  Variance   Skewness  Curtosis   Entropy
10         0   1.22470   8.777900 -2.213500 -0.806470
11         1   3.98990  -2.706600  2.394600  0.862910
12         1   1.89930   7.662500  0.153940 -3.110800
16         1   2.67190   3.064600  0.371580  0.586190
20         1   5.78670   7.890200 -2.619600 -0.487080
21         0   0.32920  -4.455200  4.571800 -0.988800
24         0   4.43380   9.887000 -4.679500 -3.748300
28         0   6.56330   9.818700 -4.411300 -3.225800
50         1   4.32390  -4.883500  3.435600 -0.577600
53         1   2.54900   6.149900 -1.160500 -1.237100
57         0   5.80700   5.009700 -2.238400  0.438780
58         0   3.13770  -4.109600  4.570100  0.989630
62         1   4.25860  11.296200 -4.094300 -4.345700
63         0   1.79390  -1.117400  1.545400 -0.260790
66         0   4.60540  -4.076500  2.758700  0.319810
71         0   4.13730   0.492480  1.093000  1.827600
75         0   2.30660   3.536400  0.575510  0.419380
79         0   1.13170   3.964700  3.397900  0.843510
93         0   2.44860  -6.317500  7.963200  0.206020
99         1  -2.74190  11.403800  2.539400 -5.579300
120        1   3.46420  10.687800 -3.407100 -4.109000
130        1   3.26970  -4.341400  3.688400 -0.298290
133        1   0.43390   5.539500  2.033000 -0.404320
137        0   5.03200   8.202600 -2.625600 -1.034100
141        1   1.73170  -0.347650  4.190500 -0.991380
144        1   3.84810  10.153900 -3.856100 -4.222800
154        1   1.93580   8.165400 -0.023425 -2.258600
155        0   2.48600  -0.995330  5.340400 -0.154750
163        0   2.40080   9.359300 -3.356500 -3.352600
164        1   4.88510   1.599500 -0.000291  1.640100
169        1   0.11739   6.276100 -1.549500 -2.474600
171        0   4.05520  -2.458300  2.280600  1.032300
178        0  -0.13144  -1.777500  8.331600  0.352140
179        0   2.39250   9.798000 -3.036100 -2.822400
181        0  -0.11783  -1.578900  8.030000 -0.028031
182        1  -0.69572   8.616500  1.841900 -4.328900
185        0  -1.25370  10.880300  1.931000 -4.323700
188        0   4.56450  -3.627500  2.868400  0.277140
197        1   1.91570   6.081600  0.237050 -2.011600
198        1   4.02150  -2.191400  2.464800  1.140900
203        0   4.17570  10.261500 -3.855200 -4.305600
204        1   0.83292   7.540400  0.650050 -0.925440
215        0   6.09190   2.967300 -1.326700  1.455100
217        0   1.32640   1.032600  5.656600 -0.413370
218        1  -0.16735   7.627400  1.206100 -3.624100
221        1   2.41960   6.466500 -0.756880  0.228000
222        0   1.09870   0.639400  5.989000 -0.582770
225        1   1.35620   3.213600  4.346500  0.786620
228        1   3.12190  -3.137000  1.925900 -0.374580
245        1   4.21340  -2.806000  2.011600  0.674120
248        0   0.37980   0.709800  0.757200 -0.444400
251        0   0.57461  10.110500 -1.691700 -4.392200
254        0   4.01020  10.656800 -4.138800 -5.064600
258        0   3.74400   0.794590  0.958510  1.007700
260        1   3.77310   7.207300 -1.681400 -0.947420
271        0   5.39150   9.994600 -3.808100 -3.364200
272        0   4.40720  -0.070365  2.041600  1.131900